version: '3.4'
services:
### ROUNDCUBE ######################
  roundcube:
    container_name: ${COMPOSE_PROJECT_NAME}_${ROUNDCUBE_CONTAINER_NAME}
    build:
      context: ./roundcube
      args: 
        - ROUNDCUBE_TAG_VERSION=${ROUNDCUBE_TAG_VERSION}
    environment: 
      - ROUNDCUBE_DEFAULT_HOST=mail.${DOMAIN}
    networks: 
      default:
        ipv4_address: ${ROUNDCUBEL_HOST}
        aliases: 
          - ${ROUNDCUBE_HOSTNAME}.${DOMAIN}
    restart: always

