version: '3.4'

### NETWORKS #######################
networks: 
  default: 
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: ${SUBNET}

### VOLUMES ########################
volumes:
  mysql_data:
  ldap_data:
  ldap_config:
  ldap_data_backup:
  bind_data:
  gitlab_data:
  gitlab_config:
  maildata:
  mailstate:
  
### SERVICES ########################
services:
### LDAP ###########################
  ldap:
    container_name: ${COMPOSE_PROJECT_NAME}_${LDAP_CONTAINER_NAME}
    hostname: ${LDAP_HOSTNAME}.${DOMAIN}
    build:
      context: ./ldap
      args: 
        - LDAP_TAG_VERSION=${LDAP_TAG_VERSION}
    volumes: 
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ldap_data_backup:/data/backup
    environment: 
      - LDAP_DOMAIN=${DOMAIN}
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_CONFIG_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_BACKUP_CONFIG_CRON_EXP=${LDAP_BACKUP_CONFIG_CRON_EXP}
      - LDAP_BACKUP_DATA_CRON_EXP=${LDAP_BACKUP_DATA_CRON_EXP}
      - LDAP_BACKUP_TTL=${LDAP_BACKUP_TTL}
    networks: 
      default:
        aliases: 
          - ${LDAP_HOSTNAME}.${DOMAIN}
    restart: always

### LDAP-CLIENT ####################
  ldap-client:
    container_name: ${COMPOSE_PROJECT_NAME}_${LDAP_CLIENT_CONTAINER_NAME}
    build:
      context: ./ldap-client
      args: 
        - LDAP_CLIENT_TAG_VERSION=${LDAP_CLIENT_TAG_VERSION}
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=${LDAP_HOSTNAME}.${DOMAIN}
    depends_on:
      - ldap
    expose:
      - ${LDAP_CLIENT_EXPOSE}
    restart: always
    networks: 
      default:
        ipv4_address: ${LDAP_CLIENT_HOST}
        aliases: 
          - ${LDAP_CLIENT_HOSTNAME}.${DOMAIN}
    
### BIND ###########################
  bind:
    container_name: ${COMPOSE_PROJECT_NAME}_${BIND_CONTAINER_NAME}
    build:
      context: ./bind
      args: 
        - BIND_TAG_VERSION=${BIND_TAG_VERSION}
    expose:
      - ${BIND_EXPOSE}
      - ${BIND_WEDMIN_EXPOSE}
    restart: always
    volumes:
      - bind_data:/data 
    networks: 
      default:
        ipv4_address: ${BIND_HOST}
        aliases: 
          - ${BIND_HOSTNAME}.${DOMAIN}

### REDMINE ########################
  redmine:
    container_name: ${COMPOSE_PROJECT_NAME}_${REDMINE_CONTAINER_NAME}
    hostname: ${REDMINE_HOSTNAME}.${DOMAIN}
    build:
      context: ./redmine
      args: 
        - REDMINE_TAG_VERSION=${REDMINE_TAG_VERSION}
    volumes: 
      - ${REDMINE_DATA_PATH}:/usr/src/redmine/files
    environment: 
      - REDMINE_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - REDMINE_DB_DATABASE=${MYSQL_DATABASE}
      - REDMINE_DB_MYSQL=${MYSQL_HOST}
    depends_on: 
      - mysql
    networks: 
      default:
        ipv4_address: ${REDMINE_HOST}
        aliases: 
          - ${REDMINE_HOSTNAME}.${DOMAIN}
    expose:
      - ${REDMINE_EXPOSE}
    restart: always

### MYSQL ##########################
  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}_${MYSQL_CONTAINER_NAME}
    build:
      context: ./mysql
      args: 
        - MYSQL_TAG_VERSION=${MYSQL_TAG_VERSION}
    environment: 
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    volumes: 
      - mysql_data:/var/lib/mysql
    networks: 
      default:
        ipv4_address: ${MYSQL_HOST}
    restart: always

### GITLAB #########################
  gitlab:
    container_name: ${COMPOSE_PROJECT_NAME}_${GITLAB_CONTAINER_NAME}
    build:
      context: ./gitlab
      args: 
        - GITLAB_TAG_VERSION=${GITLAB_TAG_VERSION}
    environment: 
      - GITLAB_OMNIBUS_CONFIG="external_url 'http://${GITLAB_HOSTNAME}.${DOMAIN}/'; gitlab_rails['lfs_enabled'] = true;"
    volumes: 
      - gitlab_data:/var/opt/gitlab
      - gitlab_config:/etc/gitlab
      - ./logs/gitlab:/var/log/gitlab
    networks: 
      default:
        ipv4_address: ${GITLAB_HOST}
        aliases: 
          - ${GITLAB_HOSTNAME}.${DOMAIN}
    restart: always



  