version: '3.4'

### NETWORKS #######################
networks: 
  default: 
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: ${SUBNET}

### VOLUMES ########################
volumes:
  mysql_data:
  ldap_data:
  ldap_config:
  ldap_data_backup:
  bind_data:
  gitlab_data:
  gitlab_config:
  maildata:
  mailstate:
  
### SERVICES ########################
services:
### LDAP ###########################
  ldap:
    container_name: ${COMPOSE_PROJECT_NAME}_${LDAP_CONTAINER_NAME}
    hostname: ${LDAP_HOSTNAME}.${DOMAIN}
    build:
      context: ./ldap
      args: 
        - LDAP_TAG_VERSION=${LDAP_TAG_VERSION}
    volumes: 
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ldap_data_backup:/data/backup
    environment: 
      - LDAP_DOMAIN=${DOMAIN}
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_CONFIG_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_BACKUP_CONFIG_CRON_EXP=${LDAP_BACKUP_CONFIG_CRON_EXP}
      - LDAP_BACKUP_DATA_CRON_EXP=${LDAP_BACKUP_DATA_CRON_EXP}
      - LDAP_BACKUP_TTL=${LDAP_BACKUP_TTL}
    networks: 
      default:
        aliases: 
          - ${LDAP_HOSTNAME}.${DOMAIN}
    restart: always

### LDAP-CLIENT ####################
  ldap-client:
    container_name: ${COMPOSE_PROJECT_NAME}_${LDAP_CLIENT_CONTAINER_NAME}
    build:
      context: ./ldap-client
      args: 
        - LDAP_CLIENT_TAG_VERSION=${LDAP_CLIENT_TAG_VERSION}
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=${LDAP_HOSTNAME}.${DOMAIN}
    depends_on:
      - ldap
    expose:
      - ${LDAP_CLIENT_EXPOSE}
    restart: always
    networks: 
      default:
        ipv4_address: ${LDAP_CLIENT_HOST}
        aliases: 
          - ${LDAP_CLIENT_HOSTNAME}.${DOMAIN}
    
### BIND ###########################
  bind:
    container_name: ${COMPOSE_PROJECT_NAME}_${BIND_CONTAINER_NAME}
    build:
      context: ./bind
      args: 
        - BIND_TAG_VERSION=${BIND_TAG_VERSION}
    expose: 
      - ${BIND_EXPOSE}
      - ${BIND_WEDMIN_EXPOSE}
    restart: always
    volumes:
      - bind_data:/data 
    networks: 
      default:
        ipv4_address: ${BIND_HOST}
        aliases: 
          - ${BIND_HOSTNAME}.${DOMAIN}

### REDMINE ########################
  redmine:
    container_name: ${COMPOSE_PROJECT_NAME}_${REDMINE_CONTAINER_NAME}
    hostname: ${REDMINE_HOSTNAME}.${DOMAIN}
    build:
      context: ./redmine
      args: 
        - REDMINE_TAG_VERSION=${REDMINE_TAG_VERSION}
    volumes: 
      - ${REDMINE_DATA_PATH}:/usr/src/redmine/files
    environment: 
      - REDMINE_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - REDMINE_DB_DATABASE=${MYSQL_DATABASE}
      - REDMINE_DB_MYSQL=${MYSQL_HOST}
    depends_on: 
      - mysql
    networks: 
      default:
        ipv4_address: ${REDMINE_HOST}
        aliases: 
          - ${REDMINE_HOSTNAME}.${DOMAIN}
    expose:
      - ${REDMINE_EXPOSE}
    restart: always

### MYSQL ##########################
  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}_${MYSQL_CONTAINER_NAME}
    build:
      context: ./mysql
      args: 
        - MYSQL_TAG_VERSION=${MYSQL_TAG_VERSION}
    environment: 
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    volumes: 
      - mysql_data:/var/lib/mysql
    networks: 
      default:
        ipv4_address: ${MYSQL_HOST}
    restart: always

### GITLAB #########################
  gitlab:
    container_name: ${COMPOSE_PROJECT_NAME}_${GITLAB_CONTAINER_NAME}
    build:
      context: ./gitlab
      args: 
        - GITLAB_TAG_VERSION=${GITLAB_TAG_VERSION}
    environment: 
      - GITLAB_OMNIBUS_CONFIG="external_url 'http://${GITLAB_HOSTNAME}.${DOMAIN}/'; gitlab_rails['lfs_enabled'] = true;"
    volumes: 
      - gitlab_data:/var/opt/gitlab
      - gitlab_config:/etc/gitlab
      - ./logs/gitlab:/var/log/gitlab
    networks: 
      default:
        ipv4_address: ${GITLAB_HOST}
        aliases: 
          - ${GITLAB_HOSTNAME}.${DOMAIN}
    restart: always

### ROUNDCUBEMAIL ##################
  roundcube:
    container_name: ${COMPOSE_PROJECT_NAME}_${ROUNDCUBEMAIL_CONTAINER_NAME}
    build:
      context: ./roundcube
      args: 
        - ROUNDCUBEMAIL_TAG_VERSION=${ROUNDCUBEMAIL_TAG_VERSION}
    volumes: 
      - ./roundcube/config/:/var/roundcube/config/
    environment: 
      - ROUNDCUBEMAIL_DEFAULT_HOST=${DOMAIN}
      - ROUNDCUBEMAIL_SMTP_SERVER=${DOMAIN}
      - ROUNDCUBEMAIL_SMTP_PORT=25
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=${MYSQL_HOST}
      - ROUNDCUBEMAIL_DB_USER=${MYSQL_USER}
      - ROUNDCUBEMAIL_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ROUNDCUBEMAIL_DB_NAME=${ROUNDCUBEMAIL_DB_NAME}
    networks: 
      default:
        ipv4_address: ${ROUNDCUBEMAIL_HOST}
        aliases: 
          - ${ROUNDCUBEMAIL_HOSTNAME}.${DOMAIN}
    expose:
      - 80
      - 443
    restart: always

### MAIL ###########################
  mail:
    hostname: ${MAIL_HOSTNAME}
    domainname: ${DOMAIN}
    container_name: ${COMPOSE_PROJECT_NAME}_${MAIL_CONTAINER_NAME}
    build:
      context: ./mail
      args: 
        - MAIL_TAG_VERSION=${MAIL_TAG_VERSION}
        - DOMAIN=${DOMAIN}
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "465:465"
      - "993:993"

    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - ./mail/config/:/tmp/docker-mailserver/
      - ./mail/ssl/:/ssl/

    environment:
      - ENABLE_SPAMASSASSIN=${ENABLE_SPAMASSASSIN}
      - ENABLE_CLAMAV=${ENABLE_CLAMAV}
      - ENABLE_FAIL2BAN=${ENABLE_FAIL2BAN}
      - ENABLE_POSTGREY=${ENABLE_POSTGREY}
      - ENABLE_SASLAUTHD=${ENABLE_SASLAUTHD}
      - ENABLE_LDAP=${ENABLE_LDAP}
      - ONE_DIR=${ONE_DIR}
      - DMS_DEBUG=${DMS_DEBUG}     
      - SA_SPAM_SUBJECT=${SA_SPAM_SUBJECT} 
      - LDAP_SERVER_HOST=${LDAP_HOSTNAME}.${DOMAIN}
      - LDAP_SEARCH_BASE=${LDAP_SEARCH_BASE}
      - LDAP_BIND_DN=${LDAP_BIND_DN}
      - LDAP_BIND_PW=${LDAP_BIND_PW}
      - LDAP_QUERY_FILTER_USER=${LDAP_QUERY_FILTER_USER}
      - LDAP_QUERY_FILTER_GROUP=${LDAP_QUERY_FILTER_GROUP}
      - LDAP_QUERY_FILTER_ALIAS=${LDAP_QUERY_FILTER_ALIAS}
      - LDAP_QUERY_FILTER_DOMAIN=${LDAP_QUERY_FILTER_DOMAIN}
      - DOVECOT_PASS_FILTER=${DOVECOT_PASS_FILTER}
      - DOVECOT_PASS_ATTRS=${DOVECOT_PASS_ATTRS}
      - DOVECOT_USER_FILTER=${DOVECOT_USER_FILTER}
      - DOVECOT_USER_ATTRS=${DOVECOT_USER_ATTRS}
      - SASLAUTHD_MECHANISMS=${SASLAUTHD_MECHANISMS}
      - SASLAUTHD_LDAP_SERVER=${LDAP_HOSTNAME}.${DOMAIN}
      - SASLAUTHD_LDAP_SEARCH_BASE=${SASLAUTHD_LDAP_SEARCH_BASE}
      - SASLAUTHD_LDAP_BIND_DN=${SASLAUTHD_LDAP_BIND_DN}
      - SASLAUTHD_LDAP_PASSWORD=${SASLAUTHD_LDAP_PASSWORD}
      - SASLAUTHD_LDAP_FILTER=${SASLAUTHD_LDAP_FILTER}
      - POSTMASTER_ADDRESS=postmaster@${DOMAIN}
      - SSL_TYPE=${SSL_TYPE}
      - PERMIT_DOCKER=${PERMIT_DOCKER}
    networks: 
      default:
        ipv4_address: ${MAIL_HOST}
        aliases: 
          - ${DOMAIN}
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
  