dist: trusty
language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
before_install:
  - rvm install 2.2
  - rvm use 2.2 --fuzzy
install:
  - gem install scss_lint
  - npm install
script:
  - npm run lint --silent
