production:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: '172.25.0.8'
      port: 25
      openssl_verify_mode: none
      domain: 'karioka.ru'
      authentication: :plain
      user_name: 'task@karioka.ru'
      password: 'defender'